name: Python CI

on:
  push:
    branches:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
        test-target: [test, quality]
        django-version: [3.2, 4.2]

    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build Docker
      run: |
        docker-compose -f .github/docker-compose-ci.yml up -d
        docker exec ecomworker bash -c "sudo apt update -y; sudo apt install python3-dev -y;"

    - name: Run Tests
      env:
        TARGETS: ${{ matrix.test-target }}
        DJANGO_VERSIONS: ${{ matrix.django-version }}
      run: |
        docker exec ecomworker bash -c "cd /edx/app/ecomworker/ecomworker && pip install django==$DJANGO_VERSIONS && make $TARGETS"

    - name: Run Coverage
      if: matrix.test-target == 'test'
      run: |
        pip install -U codecov
        codecov
