name: Upgrade Requirements

on:
  push:
      branches: [mobeenali/REV-3620]
  pull_request:
      branches:
      - '**'
  workflow_dispatch:
     inputs:
       branch:
         description: 'Target branch to create requirements PR against'
         required: true
         default: 'master'
jobs:
   call-test-upgrade-python-requirements-workflow:
    with:
       branch: ${{ github.event.inputs.branch }}
       team_reviewers: "revenue-squad"
       email_address: revenue-tasks@edx.org  
       send_success_notification: false
    secrets:
       requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
       requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
       edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
       edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
    uses: openedx/ecommerce-worker/.github/workflows/test-upgrade-python-requirements.yml@mobeenali/REV-3620
